### ISSUE TITLE
Common package in Python

### ISSUE THREAD

**Issue by gdemiollis** [firebase/geofire-android#13]
Hi @samtstern,

Thank you for this amazing library. I created a Java Cloud function with the content of the [common](https://github.com/firebase/geofire-android/tree/master/common) package, but I would like to integrate it this geofire with firestore feature to my Python appengine backend.
Do you know if there is a Python version of this [common](https://github.com/firebase/geofire-android/tree/master/common) package?

Thank you in advance.

Guilhem

**Comment by samtstern** [comment]
@gdemiollis thank you for the kind words!  There is no official geofire (or geofire-common) package in python and we don't have any plans to create one.  If you need to use it in Python you'll have to try and copy one of the Java/ObjC/JS implementations and rewrite it.
