### ISSUE TITLE
Migrate to AndroidX

### ISSUE THREAD

**Issue by warting** [firebase/geofire-android#20]
I'm trying to get rid of jetifier and this needs to be migrated to androidX.
I have created a PR: https://github.com/firebase/geofire-android/pull/17

**Comment by thatfiredev** [comment]
Fixed by #17

**Comment by thatfiredev** [comment]
@warting There's a special shotout to you on our [July Release Notes video](https://youtu.be/gD8iF0Jildk?t=99) on Youtube.
Thanks again for helping us get rid of jetifier!
