### ISSUE TITLE
GeoQuery could't fetch all user id in nearby location from a location with certain radius.

### ISSUE THREAD

**Issue by bitactro** [firebase/geofire-android#4]
This is no proper documentation about what and how actually `onKeyEntered()` function works in geoQuery works.. Like I am trying to store all userID's which is a key in `geofire` but I am only getting one userID and that is the last userID present in `GeoFire`.

I am looking for more detailed document on how to use `GeoQuery`..

**Comment by samtstern** [comment]
@bitactro there is quite a bit of documentation for `onKeyEntered`:
https://github.com/firebase/geofire-android#receiving-events-for-geo-queries

You should expect to see `onKeyEntered` fired once for each matching result and then when all of the results are done you should see `onGeoQueryReady` fire.

If that's not happening for you, please show a minimal example to help us reproduce this bug.

**Comment by bitactro** [comment]
yes correct.. thanks.. It is working good.
