### ISSUE TITLE
Play Services dependency?

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/geofire-android#8]
Since GeoFire heart is Firebase Real-time Database and RTDB will work without Play Services according to [documentation](https://firebase.google.com/docs/android/android-play-services). Can I assume that it is safe and will work completely on the device that has no Google Play Services such as Amazon Kindle device?

**Comment by samtstern** [comment]
@ArcherEmiya05 yes that's correct.  This library has no dependency on Google Play services.
